---
- name: Get dnsservers set
  delegate_to: localhost
  xml:
    path: /tmp/config-{{ inventory_hostname }}.xml
    xpath: /opnsense/system/dnsserver
    content: text
  register: configured_dnsserver

- set_fact:
    change_dns: True
  with_items: "{{ configured_dnsserver.matches }}"
  when: (item.dnsserver not in dnsserver) or (dnsserver|length) != (configured_dnsserver.matches|length)

- name: Reset dnsservers
  delegate_to: localhost
  xml:
    path: /tmp/config-{{ inventory_hostname }}.xml
    xpath: /opnsense/system/dnsserver
    state: absent
    pretty_print: yes
  when: change_dns | default(False)

- name: Dnsservers
  delegate_to: localhost
  xml:
    path: /tmp/config-{{ inventory_hostname }}.xml
    xpath: /opnsense/system
    add_children: 
      - dnsserver: "{{ item }}"
    pretty_print: yes
  when: change_dns | default(False)
  with_items: 
    "{{ dnsserver }}"
...
