---

- name: general - unset - notify handlers
  ansible.builtin.debug:
    msg: "notify {{ item.value }} for {{ unsetitem }} matching {{ item.key }}"
  changed_when: true
  with_dict: "{{ opn_unset_handlers }}"
  notify: "{{ item.value }}"
  when: unsetitem is regex(item.key)

...
