---
# vars:
#  opn_hasync:
#    - pfsyncenabled: "on"
#    - username: "root"
#    - password: "opnsense"

- name: hasync
  delegate_to: localhost
  community.general.xml:
    path: "{{ local_config_path }}"
    xpath: "/opnsense/hasync/{{ item.key }}"
    value: "{{ (item.value == None) | ternary(item.value, (item.value | string)) }}"
    pretty_print: true
  with_dict: "{{ opn_hasync | default([]) }}"
...
