# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2 smartindent nu ft=yaml
---

- name: "IPSec ike phase2 {{ uniqid }} for ikeid {{ ikeid }}"
  delegate_to: localhost
  xml:
    path: "{{ local_config_path }}"
    xpath: "/opnsense/ipsec/phase2[ikeid='{{ ikeid }}' and uniqid='{{ uniqid }}']/{{ item.key }}"
    value: "{{ item.value }}"
    pretty_print: yes
  with_dict:
    - "{{ ipsecphasevar2[uniqid] | default({}) }}"
  when:
    - not item.key == 'localid'
    - not item.key == 'remoteid'
    - not item.key == 'encryption-algorithm-options'
    - not item.key == 'hash-algorithm-options'

- name: "IPSec ike phase2 {{ uniqid }} localid for ikeid {{ ikeid }}"
  delegate_to: localhost
  xml:
    path: "{{ local_config_path }}"
    xpath: "/opnsense/ipsec/phase2[ikeid='{{ ikeid }}' and uniqid='{{ uniqid }}']/localid/{{ item.key }}"
    value: "{{ item.value }}"
    pretty_print: yes
  with_dict:
    - "{{ ipsecphasevar2[uniqid].localid | default({}) }}"

- name: "IPSec ike phase2 {{ uniqid }} remoteid for ikeid {{ ikeid }}"
  delegate_to: localhost
  xml:
    path: "{{ local_config_path }}"
    xpath: "/opnsense/ipsec/phase2[ikeid='{{ ikeid }}' and uniqid='{{ uniqid }}']/remoteid/{{ item.key }}"
    value: "{{ item.value }}"
    pretty_print: yes
  with_dict:
    - "{{ ipsecphasevar2[uniqid].remoteid | default({}) }}"

- name: "IPSec ike phase2 {{ uniqid }} count encryption-algorithm-options for ikeid {{ ikeid }}"
  delegate_to: localhost
  xml:
    path: "{{ local_config_path }}"
    xpath: "/opnsense/ipsec/phase2[ikeid='{{ ikeid }}' and uniqid='{{ uniqid }}']/encryption-algorithm-option/name"
    count: yes
  register: eao_count

- name: "IPSec ike phase2 {{ uniqid }} get encryption-algorithm-options for ikeid {{ ikeid }}"
  delegate_to: localhost
  xml:
    path: "{{ local_config_path }}"
    xpath: "/opnsense/ipsec/phase2[ikeid='{{ ikeid }}' and uniqid='{{ uniqid }}']/encryption-algorithm-option[name='{{ item.name }}']"
    count: yes
  register: encalgopt
  with_items:
    - "{{ ipsecphasevar2[uniqid]['encryption-algorithm-options'] | default([]) }}"
  when: eao_count.count > 0
- debug:
    var: encalgopt
    verbosity: 1
  when: encalgopt is defined

- name: "IPSec ike phase2 {{ uniqid }} check reset of encryption-algorithm-options for ikeid {{ ikeid }}"
  set_fact:
    encalgopt_reset: True
  when:
    - eao_count.count != (ipsecphasevar2[uniqid]['encryption-algorithm-options']|length)
- name: "IPSec ike phase2 {{ uniqid }} check reset of encryption-algorithm-options for ikeid {{ ikeid }}"
  set_fact:
    encalgopt_reset: True
  when:
    - item.count is defined and item.count == 0
  with_items:
    - "{{ encalgopt.results }}"
- debug:
    var: encalgopt_reset
    verbosity: 1
  when: encalgopt_reset is defined

- name: "IPSec ike phase2 {{ uniqid }} reset encryption-algorithm-options for ikeid {{ ikeid }}"
  delegate_to: localhost
  xml:
    path: "{{ local_config_path }}"
    xpath: "/opnsense/ipsec/phase2[ikeid='{{ ikeid }}' and uniqid='{{ uniqid }}']/encryption-algorithm-option"
    state: absent
    pretty_print: yes
  with_items:
    - "{{ ipsecphasevar2[uniqid]['encryption-algorithm-options'] | default([]) }}"
  when: encalgopt_reset|default(false)

- name: "IPSec ike phase2 {{ uniqid }} create encryption-algorithm-options for ikeid {{ ikeid }}"
  delegate_to: localhost
  xml:
    path: "{{ local_config_path }}"
    xpath: "/opnsense/ipsec/phase2[ikeid='{{ ikeid }}' and uniqid='{{ uniqid }}']"
    add_children: "[ {% for eao in ipsecphasevar2[uniqid]['encryption-algorithm-options'] -%}'<encryption-algorithm-option><name>{{ eao.name }}</name></encryption-algorithm-option>',{%- endfor %}]"
    input_type: xml
    pretty_print: yes
  when: encalgopt_reset|default(false)

- name: "IPSec ike phase2 {{ uniqid }} encryption-algorithm-options for ikeid {{ ikeid }}"
  delegate_to: localhost
  xml:
    path: "{{ local_config_path }}"
    xpath: "/opnsense/ipsec/phase2[ikeid='{{ ikeid }}' and uniqid='{{ uniqid }}']/encryption-algorithm-option[name='{{ item.name }}']/keylen"
    value: "{{ item.keylen }}"
    pretty_print: yes
  with_items:
    - "{{ ipsecphasevar2[uniqid]['encryption-algorithm-options'] | default([]) }}"
  when: item.keylen is defined

- name: "IPSec ike phase2 {{ uniqid }} for ikeid {{ ikeid }} : get hash-algorithm-option count"
  delegate_to: localhost
  xml:
    path: "{{ local_config_path }}"
    xpath: "/opnsense/ipsec/phase2[ikeid='{{ ikeid }}' and uniqid='{{ uniqid }}']/hash-algorithm-option"
    count: yes
  register: hashalgopt_count

- name: "IPSec ike phase2 {{ uniqid }} for ikeid {{ ikeid }} : get hash-algorithm-option elements"
  delegate_to: localhost
  xml:
    path: "{{ local_config_path }}"
    xpath: "/opnsense/ipsec/phase2[ikeid='{{ ikeid }}' and uniqid='{{ uniqid }}']/hash-algorithm-option"
    content: text
  register: hashalgopt
  when: hashalgopt_count.count > 0
- debug:
    var: hashalgopt
    verbosity: 1
  when: hashalgopt is defined

- set_fact:
    change_hashalgopt: True
  with_items: "{{ hashalgopt.matches }}"
  when:
    - hashalgopt is defined
    - hashalgopt.matches is defined
    - hashalgopt_count.count > 0
    - ((item['hash-algorithm-option'] not in ipsecphasevar2[uniqid]['hash-algorithm-options']) or (ipsecphasevar2[uniqid]['hash-algorithm-options']|length) != (hashalgopt.matches|length))

- set_fact:
    change_hashalgopt: True
  with_items: "{{ hashalgopt.matches }}"
  when:
    - hashalgopt_count.count == 0
    - hashalgopt is defined
    - hashalgopt.matches is defined
    - ipsecphasevar2[uniqid]['hash-algorithm-options']|length > 0

- set_fact:
    change_hashalgopt: True
  when: hashalgopt_count.count == 0 and ipsecphasevar2[uniqid]['hash-algorithm-options']|length > 0

- name: "IPSec ike phase2 {{ uniqid }} reset hash-algorithm-options for ikeid {{ ikeid }}"
  delegate_to: localhost
  xml:
    path: "{{ local_config_path }}"
    xpath: "/opnsense/ipsec/phase2[ikeid='{{ ikeid }}' and uniqid='{{ uniqid }}']/hash-algorithm-option"
    state: absent
    pretty_print: yes
  when: change_hashalgopt | default(False)

- name: "IPSec ike phase2 {{ uniqid }} hash-algorithm-options for ikeid {{ ikeid }}"
  delegate_to: localhost
  xml:
    path: "{{ local_config_path }}"
    xpath: "/opnsense/ipsec/phase2[ikeid='{{ ikeid }}' and uniqid='{{ uniqid }}']"
    add_children:
      - hash-algorithm-option: "{{ item }}"
    pretty_print: yes
  with_items:
    - "{{ ipsecphasevar2[uniqid]['hash-algorithm-options'] | default([]) }}"
  when: change_hashalgopt | default(False)

...
