---

# see defaults/main.yml

- name: construct argv for ldbsearch
  ansible.builtin.set_fact:
    _ldbsearch_argv: "{{ ['ldbsearch'] + opn_sync_users_ldap_args + ['--url='~opn_sync_users_ldap_url, '--scope='~opn_sync_users_ldap_scope, '--basedn='~opn_sync_users_ldap_basedn] + opn_sync_users_ldap_auth + [opn_sync_users_ldap_filter] + (opn_sync_users_ldap_fields.values() | list) }}"  # noqa yaml[line-length]
  no_log: "{{ nolog_ldapusersync | default(true) }}"

- name: fetch user data from ldap  # noqa no-changed-when
  delegate_to: localhost
  ansible.builtin.command:
    argv: "{{ _ldbsearch_argv }}"
  no_log: "{{ nolog_ldapusersync | default(true) }}"
  register: _ldbsearch
  changed_when: false

- name: debug ldbsearch result
  ansible.builtin.debug:
    var: _ldbsearch
    verbosity: 1

- name: parse ldap search users
  ansible.builtin.include_tasks: ldapusersyncdo.yml

...
