---
- name: monit alert settings
  delegate_to: localhost
  community.general.xml:
    path: "{{ local_config_path }}"
    xpath: "/opnsense/OPNsense/monit/alert[@uuid='{{ uuid }}']/{{ item.key }}"
    value: "{{ (item.value == None) | ternary(item.value, (item.value | string)) }}"
    pretty_print: true
  with_dict:
    - "{{ alertcfg | default({}) }}"
