---
- name: monit test settings
  delegate_to: localhost
  community.general.xml:
    path: "{{ local_config_path }}"
    xpath: "/opnsense/OPNsense/monit/test[@uuid='{{ uuid }}']/{{ item.key }}"
    value: "{{ item.value }}"
    pretty_print: true
  with_dict:
    - "{{ testcfg | default({}) }}"
