---
# example:
# opn_staticroutes:
#   - descr: route to nowhere
#     uuid: 6293069e-251e-5dbd-8594-60035417f2c8
#     settings:
#       - key: network
#         value: 100.64.0.0/10
#       - key: gateway
#         value: GW2NOWHERE  # must be defined in opn_gateways
#       - key: disabled
#         value: 0
#

- name: staticroutes
  delegate_to: localhost
  community.general.xml:
    path: "{{ local_config_path }}"
    xpath: "/opnsense/staticroutes/route[descr/text()='{{ item.0.descr }}']/{{ item.1.key }}"
    value: "{{ (item.1.value == None) | ternary(item.1.value, (item.1.value | string)) }}"
    pretty_print: true
  notify: configure routing
  with_subelements:
    - "{{ opn_staticroutes | default([]) }}"
    - settings

- name: route attribute uuid
  delegate_to: localhost
  community.general.xml:
    path: "{{ local_config_path }}"
    xpath: "/opnsense/staticroutes/route[descr/text()='{{ item.0.descr }}']"
    attribute: uuid
    value: "{{ item.0.uuid }}"
    pretty_print: true
  notify: configure routing
  with_subelements:
    - "{{ opn_staticroutes | default([]) }}"
    - settings
...
