# vim: tabstop=2 expandtab shiftwidth=2 softtabstop=2 smartindent nu ft=yaml
---

# example definition
#
# ! opn_unbound is deprecated, please use opn_unboundplus !
#
# opn_unboundplus:
#   general
#     enabled: 1
#     port: 53
#     active_interface: lan,wan  # default: empty => all
#     outgoing_interface:
#     local_zone_type: transparent
#   hosts:
#     04ac0d40-ecd0-4a1c-8603-91ce9aed08ad:  # uuid
#       enabled: 1
#       hostname: "*"
#       domain: test.de
#       rr: A
#       mxprio:
#       mx:
#       server: 10.11.12.13
#       description: test de
#   aliases:
#   ...
#
# see tests/unbound*.yml for more examples
#
# to unset a acl, host, etc. subsection, use opn_unset, for example
# opn_unset:
#   - OPNsense/unboundplus/hosts/host[@uuid='04ac0d40-ecd0-4a1c-8603-91ce9aed08ad']
#   - OPNsense/unboundplus/domains/domain[domain="test.de"]

- name: fail if we have a deprecated config
  delegate_to: localhost
  ansible.builtin.fail:
    msg: "found deprectated 'opn_unbound' setting! please use 'opn_unboundplus'!"
  when: opn_unbound is defined

- name: clean up old unbound tag
  delegate_to: localhost
  community.general.xml:
    path: "{{ local_config_path }}"
    xpath: /opnsense/unbound
    state: absent

- name: unboundplus
  ansible.builtin.include_tasks: unboundplus.yml
  vars:
    unboundplussection: "{{ _opnunbndsettings.key }}"
    unboundplussectionsettings: "{{ _opnunbndsettings.value }}"
  when: opn_unboundplus is defined
  with_dict: "{{ opn_unboundplus }}"
  loop_control:
    loop_var: _opnunbndsettings

# this is just a hackish fix for the strange empty tag handling in community.general.xml
# https://github.com/ansible-collections/community.general/issues/8361
- name: ensure all empty tags are shortened  # noqa no-handler
  delegate_to: localhost
  community.general.xml:
    path: "{{ local_config_path }}"
    xpath: /opnsense/OPNsense/unboundplus/general/fixemptytag
    value: community.general.xml is strange
    state: "{{ item }}"
  with_items:
    - present
    - absent
  when: _unbound_settings is changed or _unbound_settings_uuid is changed

...
