---

- name: zabbix agent - userparameter id config
  delegate_to: localhost
  community.general.xml:
    path: "{{ local_config_path }}"
    xpath: "/opnsense/OPNsense/ZabbixAgent/userparameters/userparameter[@uuid='{{ uuid }}']/id"
    value: "{{ uuid }}"
    pretty_print: true
  notify: restart zabbix agent

- name: zabbix agent - userparameter configs
  delegate_to: localhost
  community.general.xml:
    path: "{{ local_config_path }}"
    xpath: "/opnsense/OPNsense/ZabbixAgent/userparameters/userparameter[@uuid='{{ uuid }}']/{{ item.key }}"
    value: "{{ (item.value == None) | ternary(item.value, (item.value | string)) }}"
    pretty_print: true
  notify: restart zabbix agent
  with_dict:
    - "{{ cfg | default({}) }}"
