---
name: ansible test
on:
  pull_request:
  push:
  schedule:
    - cron: "45 5 * * 2"

jobs:
  build:
    name: ansible test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        ansible:
          - latest ansible
          - pinned ansible
        include:
          - ansible: latest ansible
            pip3deps: ansible lxml cryptography passlib
          - ansible: pinned ansible
            pip3deps: ansible==11.9.0 ansible-core==2.18.8 lxml cryptography passlib
    steps:
      - uses: actions/checkout@v4
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11
      - name: install requirements
        run: |
          python -m pip install --upgrade pip
          pip install ${{ matrix.pip3deps }}
      - name: debug versions
        run: |
          echo "which python ..."
          which python
          echo "python -VV ..."
          python -VV
          echo "pip --version ..."
          pip --version
          echo "pip list ..."
          pip list
          echo "ansible --version ..."
          ansible --version
          echo "ansible-config dump --only-changed -t all ..."
          ansible-config dump --only-changed -t all
      - name: run ansible test
        working-directory: ./test
        run: |
          ansible-playbook -e ansible_python_interpreter=$(which python) -v test.yml
